services:
  web:
    build: .
    command: bin/setup
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DOCKERIZED: "true"
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: phoenix_test_backend_development
    depends_on:
      - db

  react:
    build: ../phoenix_test_frontend
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_ENDPOINT: /api

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: phoenix_test_backend_development
